server:
  port: 8080

spring:
  cloud:
    consul:
      host: 10.68.5.195
      port: 8500
      discovery:
        register: true
        register-health-check: true
        health-check-interval: 10s
        tags:
          - calculator-8080
          - http
        health-check-path: /health
        service-name: thrift-calculator-rest-server
        instance-id: ${spring.cloud.consul.discovery.service-name}:${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
  thrift:
    server:
      service-id: test-server-rpc
      service-model: threadedSelector
      port: 25001
      worker-queue-capacity: 10000
      threaded-selector:
        accept-queue-size-per-thread: 10000
        selector-threads: 40
        min-worker-threads: 100
        max-worker-threads: 400
      discovery:
        enabled: true
        host: 10.68.5.195
        port: 8500
        tags:
          - threadedselector
          - thrift
          - test-server
        health-check:
          enabled: true
          check-interval: 10
          check-timeout: 3
